/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_screen_call_screen_init(void)
{
    lv_obj_t *shadow_obj = NULL;

    ui_screen_call = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_call, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_call, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_screen_call, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_screen_call, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_small_label_elena = ui_label_small_label_create(ui_screen_call);
    lv_obj_set_x(ui_call_small_label_elena, 0);
    lv_obj_set_y(ui_call_small_label_elena, 0);
    lv_obj_set_align(ui_call_small_label_elena, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_small_label_elena, "Elena Smith Bergman");
    lv_obj_set_style_text_color(ui_call_small_label_elena, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_small_label_elena, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_small_label_incoming = ui_label_small_label_create(ui_screen_call);
    lv_obj_set_x(ui_call_small_label_incoming, 0);
    lv_obj_set_y(ui_call_small_label_incoming, 25);
    lv_obj_set_align(ui_call_small_label_incoming, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_small_label_incoming, "Incoming Call");
    lv_obj_set_style_text_color(ui_call_small_label_incoming, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_small_label_incoming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 76);
    lv_obj_set_height(shadow_obj, 76);
    lv_obj_set_x(shadow_obj, -47);
    lv_obj_set_y(shadow_obj, -36);
    lv_obj_set_align(shadow_obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 68);
    lv_obj_set_height(shadow_obj, 68);
    lv_obj_set_x(shadow_obj, -48);
    lv_obj_set_y(shadow_obj, -38);
    lv_obj_set_align(shadow_obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_panel_call_incon1 = lv_obj_create(ui_screen_call);
    lv_obj_set_width(ui_call_panel_call_incon1, 60);
    lv_obj_set_height(ui_call_panel_call_incon1, 60);
    lv_obj_set_x(ui_call_panel_call_incon1, -50);
    lv_obj_set_y(ui_call_panel_call_incon1, -42);
    lv_obj_set_align(ui_call_panel_call_incon1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_call_panel_call_incon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_call_panel_call_incon1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_call_panel_call_incon1, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_call_panel_call_incon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_call_panel_call_incon1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_call_panel_call_incon1, lv_color_hex(0xFF5855), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_call_panel_call_incon1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_call_image_phone1 = lv_image_create(ui_call_panel_call_incon1);
    lv_image_set_src(ui_call_image_phone1, &ui_img_phone_png);
    lv_obj_set_width(ui_call_image_phone1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_image_phone1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_image_phone1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_call_image_phone1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_call_image_phone1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_call_image_phone1, 1360);

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 76);
    lv_obj_set_height(shadow_obj, 76);
    lv_obj_set_x(shadow_obj, 53);
    lv_obj_set_y(shadow_obj, -36);
    lv_obj_set_align(shadow_obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 68);
    lv_obj_set_height(shadow_obj, 68);
    lv_obj_set_x(shadow_obj, 52);
    lv_obj_set_y(shadow_obj, -38);
    lv_obj_set_align(shadow_obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_panel_call_incon2 = lv_obj_create(ui_screen_call);
    lv_obj_set_width(ui_call_panel_call_incon2, 60);
    lv_obj_set_height(ui_call_panel_call_incon2, 60);
    lv_obj_set_x(ui_call_panel_call_incon2, 50);
    lv_obj_set_y(ui_call_panel_call_incon2, -42);
    lv_obj_set_align(ui_call_panel_call_incon2, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_call_panel_call_incon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_call_panel_call_incon2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_call_panel_call_incon2, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_call_panel_call_incon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_call_panel_call_incon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_call_panel_call_incon2, lv_color_hex(0x31EF81), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_call_panel_call_incon2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_call_image_phone2 = lv_image_create(ui_call_panel_call_incon2);
    lv_image_set_src(ui_call_image_phone2, &ui_img_phone_png);
    lv_obj_set_width(ui_call_image_phone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_image_phone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_image_phone2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_call_image_phone2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_call_image_phone2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 124);
    lv_obj_set_height(shadow_obj, 124);
    lv_obj_set_x(shadow_obj, 3);
    lv_obj_set_y(shadow_obj, 26);
    lv_obj_set_align(shadow_obj, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 62, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    shadow_obj = lv_obj_create(ui_screen_call);
    lv_obj_set_width(shadow_obj, 114);
    lv_obj_set_height(shadow_obj, 114);
    lv_obj_set_x(shadow_obj, 2);
    lv_obj_set_y(shadow_obj, 24);
    lv_obj_set_align(shadow_obj, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(shadow_obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(shadow_obj, 57, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(shadow_obj, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(shadow_obj, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(shadow_obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_image_avatar = lv_image_create(ui_screen_call);
    lv_image_set_src(ui_call_image_avatar, &ui_img_avatar_png);
    lv_obj_set_width(ui_call_image_avatar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_image_avatar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_call_image_avatar, 0);
    lv_obj_set_y(ui_call_image_avatar, 20);
    lv_obj_set_align(ui_call_image_avatar, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_call_image_avatar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_call_image_avatar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_call_image_avatar, 52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_call_image_avatar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_scrolldots_scrolldots1 = ui_panel_scrolldots_create(ui_screen_call);
    lv_obj_set_x(ui_call_scrolldots_scrolldots1, 0);
    lv_obj_set_y(ui_call_scrolldots_scrolldots1, -8);

    lv_obj_set_width(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);

    lv_obj_set_width(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 8);
    lv_obj_set_height(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 8);
    lv_obj_set_x(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 11);
    lv_obj_set_y(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2),
                              lv_color_hex(0x101C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_call_scrolldots_scrolldots1, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);







    lv_obj_add_event_cb(ui_screen_call, ui_event_screen_call, LV_EVENT_ALL, NULL);

}
